### ISSUE TITLE
Question on the data format for generated samples of ENZYMES dataset

### ISSUE THREAD

**Issue by lizaitang** [harryjo97/GDSS#10]
Dear Authors, this project really helps a lot, I have a question that how can we transform the samples in the pkl file to dgl graph with node features for some classifiers using standard PyG enzymes or dgl. It seems that no node features in the networkx graph we generated, thanks.

**Comment by harryjo97** [comment]
Hi, thanks for your interest in our work.

In our code for the generation of generic graphs (including enzymes), only the adjacency matrices (without node features) of the generated graphs are saved as a networkx graphs. 
You can save the generated node features too by adding them as labels to the networkx nodes.

**Comment by lizaitang** [comment]
Thank you so much, do you mean that your code will also generate node features but you did not save it by default? Will it be similar to original dataset?

**Comment by harryjo97** [comment]
Yes, we generate the node features and the adjacency matrices together:
https://github.com/harryjo97/GDSS/blob/0323b0318fae66947005334445b904a05f83d118/sampler.py#L67

For general graphs (including enzymes), we have used the one-hot represented degree as the node features. 
But you can use our framework to generate other type of features.

**Comment by lizaitang** [comment]
Thanks for your reply, can the generated features transform to some common data format like ENZYMES_node_attributes.txt  used by many graph classifiers? If not , how can I use your framework to generate such kind of features? Thanks

**Comment by lizaitang** [comment]
Thanks for your reply, can the generated features transform to some common data format like ENZYMES_node_attributes.txt  used by many graph classifiers? If not , how can I use your framework to generate such kind of features? Thanks.

**Comment by lizaitang** [comment]
Thanks for your reply, can the generated features transform to some common data format like ENZYMES_node_attributes.txt  used by many graph classifiers? If not , how can I use your framework to generate such kind of features? Thanks.

**Comment by lizaitang** [comment]
Thanks for your reply, can the generated features transform to some common data format like ENZYMES_node_attributes.txt  used by many graph classifiers? If not , how can I use your framework to generate such kind of features? Thanks.

**Comment by lizaitang** [comment]
Thanks for your reply, can the generated features transform to some common data format like ENZYMES_node_attributes.txt  used by many graph classifiers? If not , how can I use your framework to generate such kind of features? Thanks.
