### ISSUE TITLE
error in generating QM9 samples

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [harryjo97/GDSS#12]
Thanks for your code first!
My problem is : when I run the command `python main.py --type sample --config sample_qm9`, I got the following error:
![image](https://github.com/harryjo97/GDSS/assets/59307253/aff73948-b162-47a6-ab0c-a7c8ddb3cc5c)
I'm using `mini-moses` repository, but when I switched to use `moses` repository, the same error occurred.
I appreciate it if you will help me with it : )

**Comment by harryjo97** [comment]
Hi, 
I never had such a case so far, and I assume there is a version compatibility issue for numpy or pickle.
Maybe you could look into this: https://github.com/davidsandberg/facenet/issues/260

**Comment by koalaaaaaaaaa** [comment]
thanks a lot!
