### ISSUE TITLE
bug with orca file

### ISSUE THREAD

**Issue by Houssemsouid** [harryjo97/GDSS#9]
Faced an issue while evaluating the model by the orca file when I runned the code on Enzymes dataset. It also didn't get into further rounds for evaluation.
![image](https://user-images.githubusercontent.com/50356516/207809810-88d75869-11f6-4a38-9d57-a73bccdf4b15.png)

**Comment by harryjo97** [comment]
Hi, 

I think the issue could be solved by compiling the ORCA program as described in Preparations.
For the evaluation of generic graph generation tasks, run the following command to compile the ORCA program (see http://www.biolab.si/supp/orca/orca.html):
```sh
cd evaluation/orca 
g++ -O2 -std=c++11 -o orca orca.cpp
```
If you have any further questions, I would be happy to answer them!
